import { store, isModerator } from '../core/state.js';
import { t } from '../core/i18n.js';
import { esc, toast } from '../core/utils.js';
import { publishContent, updateSiteSettings, getSiteSettings } from '../services/contentService.js';
import { searchUsers, moderateUser, softDeleteUser } from '../services/userService.js';
import { listAppeals, updateAppeal } from '../services/reportService.js';
import { openAuthModal } from '../components/authModal.js';
import { createNotification } from '../services/notificationService.js';
export async function adminView(query){
 if(!store.user) return [`<section class="section"><button class="retro-btn primary" id="needLogin">${t('login')}</button></section>`,r=>r.querySelector('#needLogin').onclick=openAuthModal];
 if(!isModerator()) return [`<section class="section"><h1>403</h1><p>Доступ тільки для Administrator або Moderator.</p></section>`,null];
 const tab=query.tab||'publish'; const tabs=[['publish','Публікація'],['users','Модерація користувачів'],['appeals','Скарги і пропозиції'],['queue','Запропоновані моди'],['site','Налаштування сайту']];
 let body=''; if(tab==='publish') body=publishTab(); if(tab==='users') body=await usersTab(query.user||''); if(tab==='appeals') body=await appealsTab(); if(tab==='queue') body=await queueTab(); if(tab==='site') body=await siteTab();
 return [`<section class="section admin-layout"><div class="section-head"><h1>${t('admin')}</h1></div><div class="tabs">${tabs.map(([k,l])=>`<a class="tab ${tab===k?'active':''}" href="#/admin?tab=${k}">${l}</a>`).join('')}</div>${body}</section>`,attach];
}
function publishTab(){ return `<form class="form" id="publishForm"><div class="field"><label>Зона публікації</label><select class="select" name="type"><option value="mods">Моди</option><option value="news">Новини</option></select></div><div class="field"><label>Назва</label><input class="input" name="title" required></div><div class="field"><label>Короткий опис</label><textarea class="textarea" name="description" maxlength="420" required></textarea></div><div class="field"><label>Повний текст / опис сторінки</label><textarea class="textarea" name="body" required></textarea></div><div class="field"><label>Головна картинка URL</label><input class="input" name="coverUrl"></div><div class="field"><label>Галерея URL через кому</label><input class="input" name="images"></div><div class="field"><label>Категорія / версія / версії гри</label><input class="input" name="category" placeholder="Трактори"><input class="input" name="modVersion" placeholder="1.0.0"><input class="input" name="gameVersions" placeholder="FS20, FS23"></div><div class="field"><label>Посилання завантаження</label><input class="input" name="downloadUrl"></div><button class="retro-btn primary" type="submit">Опублікувати</button></form><div class="section"><h3>Конструктор новин</h3><p class="mono-muted">Блочний конструктор підтримує до 10 блоків у полі “Повний текст”: текст, фото URL, опитування. Для складного редактора залишено чисту точку розширення.</p></div>`; }
async function usersTab(term){ const users=await searchUsers(term); return `<form class="row" id="userSearch"><input class="input" name="q" placeholder="ID, Email або Ім’я" value="${esc(term)}"><button class="retro-btn">Пошук</button></form><div>${users.map(u=>`<div class="user-row"><img class="mini-avatar" src="${esc(u.avatarUrl||'src/assets/default-avatar.svg')}"><div><b>${esc(u.name||'User')}</b> <span class="badge">#${esc(u.publicId||u.uid)}</span><p class="mono-muted">${esc(u.email||'')} · ${(u.roles||[]).at(-1)||'User'}</p></div><div class="dropdown-wrap"><button class="icon-btn" data-user-menu="${u.id}">⋯</button></div></div>`).join('')}</div>`; }
async function appealsTab(){ const items=await listAppeals(); return `<div>${items.map(a=>`<div class="appeal-row status-${a.status||'new'}"><span>${a.kind==='report'?'⚠':'✉'}</span><div><b>${esc(a.kind||'appeal')} · ${esc(a.status||'new')}</b><p class="mono-muted">Ціль: ${esc(a.targetType||'')} / ${esc(a.targetId||'')} · Автор: ${esc(a.authorName||'')}</p><p>${esc(a.text||'')}</p></div><div class="row"><button class="retro-btn" data-ap="${a.id}" data-status="working">В роботі</button><button class="retro-btn" data-ap="${a.id}" data-status="closed">Закрите</button><button class="retro-btn" data-reply-ap="${a.id}" data-uid="${a.authorUid}">Відповісти</button></div></div>`).join('')||`<div class="empty-state">${t('empty')}</div>`}</div>`; }
async function queueTab(){ return `<div class="empty-state">Черга запропонованих модів читається з collection <b>modSubmissions</b>. Кнопки Схвалити / Редагувати / Відхилити підготовлені у схемі README.</div>`; }
async function siteTab(){ const s=await getSiteSettings(); return `<form class="form" id="siteSettings"><label class="row"><input type="checkbox" name="seasonal" ${s.seasonal?'checked':''}> Увімкнути сезонне оформлення</label><label class="row"><input type="checkbox" name="maintenance" ${s.maintenance?'checked':''}> Увімкнути технічне обслуговування</label><label class="row"><input type="checkbox" name="announcementEnabled" ${s.announcementEnabled?'checked':''}> Увімкнути банер у шапці</label><input class="input" name="announcementText" value="${esc(s.announcementText||'')}" placeholder="Текст оголошення"><input class="input" name="announcementUrl" value="${esc(s.announcementUrl||'')}" placeholder="URL"><button class="retro-btn primary">${t('save')}</button></form>`; }
function attach(root){
 root.querySelector('#publishForm')?.addEventListener('submit',async e=>{e.preventDefault(); const fd=Object.fromEntries(new FormData(e.target).entries()); try{await publishContent(fd.type,{title:fd.title,description:fd.description,body:fd.body,coverUrl:fd.coverUrl,images:fd.images?fd.images.split(',').map(s=>s.trim()).filter(Boolean):[],category:fd.category,modVersion:fd.modVersion,gameVersions:fd.gameVersions?fd.gameVersions.split(',').map(s=>s.trim()):[],downloadUrl:fd.downloadUrl});toast('Опубліковано');e.target.reset();}catch(err){toast(err.message,'err')}});
 root.querySelector('#userSearch')?.addEventListener('submit',e=>{e.preventDefault(); location.hash=`#/admin?tab=users&user=${encodeURIComponent(new FormData(e.target).get('q'))}`});
 root.querySelectorAll('[data-user-menu]').forEach(b=>b.onclick=()=>userMenu(b));
 root.querySelectorAll('[data-ap]').forEach(b=>b.onclick=async()=>{await updateAppeal(b.dataset.ap,{status:b.dataset.status});toast('Статус оновлено');location.reload();});
 root.querySelectorAll('[data-reply-ap]').forEach(b=>b.onclick=async()=>{const text=prompt('Відповідь користувачу'); if(text){await createNotification(b.dataset.uid,{type:'appeal_reply',title:'Відповідь адміністрації',text,link:'#/feedback?tab=mine'});toast('Відповідь надіслано')}});
 root.querySelector('#siteSettings')?.addEventListener('submit',async e=>{e.preventDefault(); const fd=new FormData(e.target); await updateSiteSettings({seasonal:fd.has('seasonal'),maintenance:fd.has('maintenance'),announcementEnabled:fd.has('announcementEnabled'),announcementText:fd.get('announcementText'),announcementUrl:fd.get('announcementUrl')});toast('Налаштування збережено')});
}
function userMenu(btn){ const uid=btn.dataset.userMenu; const wrap=btn.closest('.dropdown-wrap'); wrap.innerHTML+=`<div class="dropdown"><a class="dropdown-item" href="#/profile/${uid}">Переглянути профіль</a><button class="dropdown-item" data-mute>Замутити/Розмутити</button><button class="dropdown-item" data-ban>Заблокувати/Розблокувати</button><button class="dropdown-item" data-rating>Рейтинг +/-</button><button class="dropdown-item" data-role>Редагувати ролі</button><button class="dropdown-item" data-deluser>Видалити акаунт</button></div>`; const d=wrap.querySelector('.dropdown'); d.querySelector('[data-mute]').onclick=()=>moderateUser(uid,{mutedUntil:new Date(Date.now()+86400000).toISOString()}); d.querySelector('[data-ban]').onclick=()=>moderateUser(uid,{blocked:true}); d.querySelector('[data-rating]').onclick=()=>{const v=Number(prompt('Балів +/-')); if(Number.isFinite(v))moderateUser(uid,{ratingManualDelta:v});}; d.querySelector('[data-role]').onclick=()=>{const roles=prompt('Ролі через кому: User,Author,Moderator,Administrator'); if(roles)moderateUser(uid,{roles:roles.split(',').map(s=>s.trim())});}; d.querySelector('[data-deluser]').onclick=()=>softDeleteUser(uid); }
