import { getContent, voteContent, incrementDownloads } from '../services/contentService.js';
import { listComments, addComment, deleteComment, voteComment } from '../services/commentService.js';
import { pickText, localeDate, t } from '../core/i18n.js';
import { store, isModerator } from '../core/state.js';
import { $, esc, htmlLinks, toast } from '../core/utils.js';
import { openAuthModal } from '../components/authModal.js';
import { openReportModal } from './shared.js';
export async function detailView(type,id,query){
 const item=await getContent(type,id); if(!item) return [`<section class="section"><h1>404</h1></section>`,null];
 const comments=await listComments(type,id); const tree=buildTree(comments);
 const images=item.images?.length?item.images:[item.coverUrl||'src/assets/default-cover.svg'];
 const html=`<section class="section"><div class="detail-hero"><div><div class="gallery-main"><img id="mainImg" src="${esc(images[0])}" alt=""></div><div class="thumbs">${images.map((im,i)=>`<button data-img="${esc(im)}"><img src="${esc(im)}" alt="${i+1}"></button>`).join('')}</div></div><div class="stack"><h1 class="pixel-title">${esc(pickText(item,'title'))}</h1><p class="mono-muted">${esc(pickText(item,'description'))}</p><div class="row"><span class="badge">${t('rating')}: ★ ${(item.ratingAvg||0).toFixed(1)} (${item.ratingCount||0})</span><span class="badge">${t('author')}: ${esc(item.authorName||'Polux')}</span></div><div class="stack"><span>${t('published')}: ${localeDate(item.createdAt)}</span>${item.category?`<span>${t('category')}: ${esc(item.category)}</span>`:''}${item.modVersion?`<span>${t('version')}: ${esc(item.modVersion)}</span>`:''}${item.gameVersions?.length?`<span>${t('gameVersion')}: ${item.gameVersions.map(esc).join(', ')}</span>`:''}</div>${type==='mods'?`<div class="row actions-mobile"><a class="retro-btn primary" id="downloadBtn" href="${esc(item.downloadUrl||'#')}">${t('download')}</a>${[1,2,3,4,5].map(n=>`<button class="retro-btn" data-rate="${n}">★${n}</button>`).join('')}</div>`:''}</div></div></section><section class="section"><h2>${type==='mods'?'Опис моду':'Текст новини'}</h2><div class="mono-muted">${htmlLinks(pickText(item,'body')||pickText(item,'description'))}</div></section><section class="section" id="comments"><div class="section-head"><h2>${t('comments')}</h2></div>${commentForm(type,id,item.authorUid)}<div id="commentList">${tree.map(c=>commentHtml(c)).join('')||`<div class="empty-state">${t('empty')}</div>`}</div></section>`;
 return [html,(root)=>attach(root,item,type,id)];
}
function buildTree(list){ const map=new Map(list.map(c=>[c.id,{...c,children:[]}])); const roots=[]; for(const c of map.values()){ if(c.parentId&&map.has(c.parentId)) map.get(c.parentId).children.push(c); else roots.push(c); } return roots; }
function commentForm(type,id,targetAuthorUid,parentId='',parentAuthorUid=''){ if(!store.user) return `<div class="empty-state"><button class="retro-btn primary" id="commentLogin">${t('login')}</button></div>`; return `<form class="form comment-form" data-parent="${parentId}" data-parent-author="${parentAuthorUid}" data-target-author="${targetAuthorUid||''}"><div class="field"><textarea class="textarea" name="text" maxlength="900" placeholder="Коментар..."></textarea></div><div class="field"><input class="input" name="imageUrl" placeholder="URL картинки (опційно)"></div><button class="retro-btn primary" type="submit">${t('send')}</button></form>`; }
function commentHtml(c){ const canDelete=store.user&&(store.user.uid===c.authorUid||isModerator()); const score=c.score||0; return `<article class="comment" id="comment-${c.id}"><div class="comment-head"><img class="mini-avatar" src="${esc(c.authorAvatar||'src/assets/default-avatar.svg')}"><div><b>${esc(c.authorName||'User')} <span class="mono-muted">#${esc(c.authorId||'')}</span></b><div><span class="badge role-badge">${esc(c.authorRole||'User')}</span> <small class="mono-muted">${localeDate(c.createdAt)}</small></div></div><div style="margin-left:auto" class="dropdown-wrap"><button class="icon-btn" data-cmenu="${c.id}" data-author="${c.authorUid}">⋯</button></div></div><p class="comment-text">${c.deleted?t('deletedComment'):htmlLinks(c.text||'')}</p>${c.imageUrl&&!c.deleted?`<img class="card-img" src="${esc(c.imageUrl)}" alt="comment image">`:''}<div class="row"><button class="retro-btn" data-vote="1" data-cid="${c.id}">▲</button><span class="vote-score ${score>0?'positive':score<0?'negative':''}">${score}</span><button class="retro-btn" data-vote="-1" data-cid="${c.id}">▼</button><button class="retro-btn" data-reply="${c.id}" data-author-name="${esc(c.authorName||'User')}" data-author="${c.authorUid}">${t('reply')}</button>${canDelete?`<button class="retro-btn danger" data-del="${c.id}">${t('delete')}</button>`:''}</div><div class="reply-slot" id="reply-${c.id}"></div>${c.children.map(commentHtml).join('')}</article>`; }
function attach(root,item,type,id){
 root.querySelectorAll('.thumbs button').forEach(b=>b.onclick=()=>$('#mainImg',root).src=b.dataset.img); $('#mainImg',root)?.addEventListener('click',()=>lightbox(root,$('#mainImg',root).src));
 root.querySelector('#downloadBtn')?.addEventListener('click',()=>incrementDownloads(type,id)); root.querySelectorAll('[data-rate]').forEach(b=>b.onclick=async()=>{try{await voteContent(type,id,Number(b.dataset.rate));toast('Голос збережено');location.reload()}catch(e){toast(e.message,'err')}});
 root.querySelector('#commentLogin')?.addEventListener('click',()=>openAuthModal()); attachCommentForms(root,type,id,item.authorUid);
 root.querySelectorAll('[data-reply]').forEach(b=>b.onclick=()=>{ if(!store.user){openAuthModal();return;} const slot=$(`#reply-${b.dataset.reply}`,root); slot.innerHTML=commentForm(type,id,item.authorUid,b.dataset.reply,b.dataset.author); slot.querySelector('textarea').value=`@${b.dataset.authorName}, `; attachCommentForms(root,type,id,item.authorUid); });
 root.querySelectorAll('[data-del]').forEach(b=>b.onclick=async()=>{await deleteComment(b.dataset.del);location.reload();});
 root.querySelectorAll('[data-vote]').forEach(b=>b.onclick=async()=>{try{await voteComment(b.dataset.cid,Number(b.dataset.vote));location.reload()}catch(e){toast(e.message,'err')}});
 root.querySelectorAll('[data-cmenu]').forEach(b=>b.onclick=()=>openReportModal({targetType:'comment',targetId:b.dataset.cmenu,targetUid:b.dataset.author}));
}
function attachCommentForms(root,type,id,targetAuthorUid){ root.querySelectorAll('.comment-form').forEach(f=>{ if(f.dataset.ready)return; f.dataset.ready='1'; f.onsubmit=async e=>{e.preventDefault(); const fd=Object.fromEntries(new FormData(f).entries()); if(!fd.text.trim())return; await addComment({targetType:type,targetId:id,targetAuthorUid,parentId:f.dataset.parent||null,parentAuthorUid:f.dataset.parentAuthor||null,text:fd.text,imageUrl:fd.imageUrl}); location.reload();}; }); }
function lightbox(root,src){ let zoom=1; const d=document.createElement('div'); d.className='lightbox'; d.innerHTML=`<img src="${esc(src)}"><button class="close-btn" style="position:absolute;right:18px;top:18px">✕</button><div class="row" style="position:absolute;bottom:18px"><button class="retro-btn" data-z="-.25">−</button><button class="retro-btn" data-z=".25">+</button></div>`; document.body.appendChild(d); d.querySelector('.close-btn').onclick=()=>d.remove(); d.querySelectorAll('[data-z]').forEach(b=>b.onclick=()=>{zoom=Math.max(1,Math.min(3,zoom+Number(b.dataset.z)));d.querySelector('img').style.transform=`scale(${zoom})`;}); }
