import { store } from '../core/state.js';
import { t } from '../core/i18n.js';
import { esc, toast } from '../core/utils.js';
import { openAuthModal } from '../components/authModal.js';
import { createReport, listAppeals } from '../services/reportService.js';
export async function feedbackView(query){
 const tab=query.tab||'submit';
 if(!store.user) return [`<section class="section"><div class="empty-state"><button class="retro-btn primary" id="needLogin">${t('login')}</button></div></section>`,r=>r.querySelector('#needLogin').onclick=openAuthModal];
 let body=''; if(tab==='mine'){ const items=await listAppeals({mine:true}); body=`${items.map(a=>`<div class="appeal-row status-${a.status}"><span>${a.kind==='report'?'⚠':'✉'}</span><div><b>${esc(a.topic||a.reason||'Звернення')}</b><p class="mono-muted">Статус: ${esc(a.status||'new')}</p><p>${esc(a.text||'')}</p>${a.answer?`<p><b>Відповідь:</b> ${esc(a.answer)}</p>`:''}</div></div>`).join('')||`<div class="empty-state">${t('empty')}</div>`}`; } else body=`<form class="form" id="feedbackForm"><div class="field"><label>Тема</label><select class="select" name="topic"><option>Проблема з сайтом</option><option>Модерація</option><option>Пропозиція</option><option value="other">Інше</option></select><input class="input hidden" name="customTopic" placeholder="Своя тема"></div><div class="field"><label>Опис до 300 символів</label><textarea class="textarea" name="text" maxlength="300" required></textarea><span class="counter">0/300</span></div><div class="field"><label>Картинка URL</label><input class="input" name="imageUrl"></div><button class="retro-btn primary">${t('send')}</button></form>`;
 return [`<section class="section"><div class="section-head"><h1>${t('feedback')}</h1></div><div class="tabs"><a class="tab ${tab==='submit'?'active':''}" href="#/feedback?tab=submit">${t('submitAppeal')}</a><a class="tab ${tab==='mine'?'active':''}" href="#/feedback?tab=mine">${t('myAppeals')}</a></div>${body}</section>`,attach];
}
function attach(root){ const form=root.querySelector('#feedbackForm'); if(!form)return; const sel=form.topic, custom=form.customTopic, ta=form.text; sel.onchange=()=>custom.classList.toggle('hidden',sel.value!=='other'); ta.oninput=()=>root.querySelector('.counter').textContent=`${ta.value.length}/300`; form.onsubmit=async e=>{e.preventDefault(); const fd=Object.fromEntries(new FormData(form).entries()); await createReport({kind:'feedback',topic:fd.topic==='other'?fd.customTopic:fd.topic,text:fd.text,imageUrl:fd.imageUrl}); toast('Звернення надіслано'); location.hash='#/feedback?tab=mine';}; }
