import { store } from './state.js';
export const L = {
uk:{home:'Головна',mods:'Моди',news:'Новини',feedback:'Зворотній зв’язок',about:'Про нас',login:'Вхід / Реєстрація',logout:'Вихід',profile:'Профіль',notifications:'Сповіщення',myMods:'Мої моди',settings:'Налаштування',admin:'Адмін-панель',viewAll:'Переглянути всі',go:'Перейти',newMods:'Нові моди',popularMods:'Найбільш популярні моди',latestNews:'Новини',empty:'Поки що тут порожньо.',loading:'Завантаження',theme:'Тема',language:'Мова',crt:'CRT',keep:'Залишити',changeLang:'Змінити мову',email:'Email',password:'Пароль',password2:'Підтвердження пароля',name:'Ім’я акаунта',signIn:'Увійти',signUp:'Зареєструватися',forgot:'Забули пароль?',send:'Надіслати',save:'Зберегти',cancel:'Скасувати',required:'Поле обов’язкове',badEmail:'Введіть коректний email з @ та доменом',passMismatch:'Паролі не збігаються',passShort:'Мінімум 6 символів',thanks:'Подяка',report:'Поскаржитись',reply:'Відповісти',delete:'Видалити',deletedComment:'[Коментар було видалено]',comments:'Коментарі',download:'Завантажити',rating:'Рейтинг',author:'Автор',category:'Категорія',version:'Версія',gameVersion:'Версія гри',published:'Опубліковано',submitAppeal:'Подати звернення',myAppeals:'Мої звернення',maintenance:'Сайт на сервісному обслуговуванні, вибачте за незручності'},
ru:{home:'Главная',mods:'Моды',news:'Новости',feedback:'Обратная связь',about:'О нас',login:'Вход / Регистрация',logout:'Выход',profile:'Профиль',notifications:'Уведомления',myMods:'Мои моды',settings:'Настройки',admin:'Админ-панель',viewAll:'Смотреть все',go:'Перейти',newMods:'Новые моды',popularMods:'Самые популярные моды',latestNews:'Новости',empty:'Пока здесь пусто.',loading:'Загрузка',theme:'Тема',language:'Язык',crt:'CRT',keep:'Оставить',changeLang:'Изменить язык',email:'Email',password:'Пароль',password2:'Подтверждение пароля',name:'Имя аккаунта',signIn:'Войти',signUp:'Зарегистрироваться',forgot:'Забыли пароль?',send:'Отправить',save:'Сохранить',cancel:'Отмена',required:'Поле обязательно',badEmail:'Введите корректный email с @ и доменом',passMismatch:'Пароли не совпадают',passShort:'Минимум 6 символов',thanks:'Благодарность',report:'Пожаловаться',reply:'Ответить',delete:'Удалить',deletedComment:'[Комментарий был удалён]',comments:'Комментарии',download:'Скачать',rating:'Рейтинг',author:'Автор',category:'Категория',version:'Версия',gameVersion:'Версия игры',published:'Опубликовано',submitAppeal:'Подать обращение',myAppeals:'Мои обращения',maintenance:'Сайт на сервисном обслуживании, извините за неудобства'},
en:{home:'Home',mods:'Mods',news:'News',feedback:'Feedback',about:'About',login:'Sign in / Sign up',logout:'Log out',profile:'Profile',notifications:'Notifications',myMods:'My mods',settings:'Settings',admin:'Admin panel',viewAll:'View all',go:'Open',newMods:'New mods',popularMods:'Most popular mods',latestNews:'News',empty:'Nothing here yet.',loading:'Loading',theme:'Theme',language:'Language',crt:'CRT',keep:'Keep',changeLang:'Change language',email:'Email',password:'Password',password2:'Confirm password',name:'Account name',signIn:'Sign in',signUp:'Sign up',forgot:'Forgot password?',send:'Send',save:'Save',cancel:'Cancel',required:'This field is required',badEmail:'Enter a valid email with @ and domain',passMismatch:'Passwords do not match',passShort:'At least 6 characters',thanks:'Thanks',report:'Report',reply:'Reply',delete:'Delete',deletedComment:'[Comment was deleted]',comments:'Comments',download:'Download',rating:'Rating',author:'Author',category:'Category',version:'Version',gameVersion:'Game version',published:'Published',submitAppeal:'Submit request',myAppeals:'My requests',maintenance:'Site is under maintenance, sorry for the inconvenience'},
pl:{home:'Start',mods:'Mody',news:'Aktualności',feedback:'Kontakt',about:'O nas'},de:{home:'Start',mods:'Mods',news:'News',feedback:'Feedback',about:'Über uns'},es:{home:'Inicio',mods:'Mods',news:'Noticias',feedback:'Contacto',about:'Sobre nosotros'},fr:{home:'Accueil',mods:'Mods',news:'Actus',feedback:'Retour',about:'À propos'}
};
export function t(key){ return L[store.lang]?.[key] || L.uk[key] || key; }
export function localeDate(value){
  const date = value?.toDate ? value.toDate() : value ? new Date(value) : null;
  if(!date || Number.isNaN(+date)) return '—';
  return new Intl.DateTimeFormat(store.lang,{dateStyle:'medium',timeStyle:'short'}).format(date);
}
export function pickText(item, field){
  if(!item) return '';
  return item.i18n?.[store.lang]?.[field] || item.i18n?.uk?.[field] || item[field] || '';
}
